/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp6;

/**
 *
 * @author pc
 */
public class vistaBorrarClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaBorrarClientes
     */
    public vistaBorrarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelCiudad = new javax.swing.JLabel();
        jTextFieldTel = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabelBusqueda = new javax.swing.JLabel();
        jTextFieldApe = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldCiudad = new javax.swing.JTextField();
        jLabelApe = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();

        setForeground(new java.awt.Color(0, 0, 255));

        jButtonSalir.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(0, 0, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelCiudad.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabelCiudad.setForeground(new java.awt.Color(0, 0, 255));
        jLabelCiudad.setText("CIUDAD");

        jTextFieldTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelActionPerformed(evt);
            }
        });

        jLabelBusqueda.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelBusqueda.setForeground(new java.awt.Color(0, 0, 255));
        jLabelBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusqueda.setText("Borrar Clientes");

        jLabelTel.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabelTel.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTel.setText("TELEFONO");

        jLabelApellido.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(0, 0, 255));
        jLabelApellido.setText("DNI:");

        jLabelApe.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabelApe.setForeground(new java.awt.Color(0, 0, 255));
        jLabelApe.setText("APELLIDO");

        jLabelNom.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabelNom.setForeground(new java.awt.Color(0, 0, 255));
        jLabelNom.setText("NOMBRE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelApe)
                    .addComponent(jLabelNom)
                    .addComponent(jLabelCiudad)
                    .addComponent(jLabelApellido)
                    .addComponent(jLabelTel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldApe)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addGap(101, 101, 101)
                .addComponent(jButtonSalir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabelBusqueda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCiudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelApe;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelBusqueda;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JTextField jTextFieldApe;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables
}
